import pandas as pd
import numpy as np

# Download the CSV-file, meaning the metadata 
df = pd.read_csv('ptbxl_database.csv', index_col ='ecg_id') #ecg_id 

# This is the first look of the original dataset:
print("ORIGINAL DATASET:")
print(df.head())
print('\n MISSING VALUES IN THE DATASET:')
print(df.isnull().sum()) 


# I drop these columns because i do not find them fit for the analysis to the ECG signals. Therefore not relevant to the signals (This is subjetive), but i can always add or remove some of them back if needed. 
df = df.drop(columns = ['height', 
    'report',
    'weight',
    'nurse', 
    'site', 
    'device', 
    'recording_date', 
    'infarction_stadium1', 
    'infarction_stadium2', 
    'validated_by', 
    'second_opinion', 
    'initial_autogenerated_report', 
    'validated_by_human', 
    ])

# Filling up remaining NaN values with 0
df = df.fillna(0) 


# Codes for the different diagnoses are in here,
# but since they are in a string-dictionary format i need to unpack them.
print(df['scp_codes'].head()) 

diagnose_codes = df['scp_codes'] 

# The eval functions converts the string into a dictionary format, while the if isinstance checks if the value is a string or not, else it will just return the value as it is. 
dictionary_list = [eval(x) if isinstance(x, str) else x for x in diagnose_codes] 

diagnose_table = pd.DataFrame(dictionary_list, index = df.index) 

diagnose_telling = diagnose_table.count().sort_values(ascending=False)
print('\n')
print("All diagnoses and how many patients that have them: ")
print(diagnose_telling.to_string())
print('\n')

diagnose_table = diagnose_table.fillna(0)

# I join the two datamframes togheter and drop the scp_codes column because the diagnoses are now in their own columns
df_cleaned_data = df.join(diagnose_table)
df_cleaned_data = df_cleaned_data.drop(columns=['scp_codes'])


print("CLEANED DATASET:")
print(df_cleaned_data.shape)
print(df_cleaned_data.isnull().sum().sum())
print(df_cleaned_data.head())

# I save a cleaned version of the dataset and i make it a csv-file so i can continue with this set for the ECG preprocessing signals.
df_cleaned_data.to_csv('cleaned_ptbxl_database.csv', index = True) 

